include_directories(${MEDIA_SDK_HEADER_DIR})
link_directories(${MEDIA_SDK_LINK_DIR})

list(APPEND LIB_VSF_SDK_NAME "z")
list(APPEND LIB_VSF_SDK_NAME "drm")
list(APPEND LIB_VSF_SDK_NAME "asound")
list(APPEND LIB_VSF_SDK_NAME "avcodec")
list(APPEND LIB_VSF_SDK_NAME "avformat")
list(APPEND LIB_VSF_SDK_NAME "avutil")
list(APPEND LIB_VSF_SDK_NAME "jpeg")
list(APPEND LIB_VSF_SDK_NAME "md_share")
list(APPEND LIB_VSF_SDK_NAME "od_share")
list(APPEND LIB_VSF_SDK_NAME "rga")
list(APPEND LIB_VSF_SDK_NAME "rkaiq")
list(APPEND LIB_VSF_SDK_NAME "RKAP_3A")
list(APPEND LIB_VSF_SDK_NAME "RKAP_ANR")
list(APPEND LIB_VSF_SDK_NAME "RKAP_Common")
list(APPEND LIB_VSF_SDK_NAME "rockchip_mpp")
list(APPEND LIB_VSF_SDK_NAME "swresample")
list(APPEND LIB_VSF_SDK_NAME "v4l2")
list(APPEND LIB_VSF_SDK_NAME "v4lconvert")
list(APPEND LIB_VSF_SDK_NAME "easymedia")

#list(APPEND LIB_ALG_SDK_NAME "tracker")
#list(APPEND LIB_ALG_SDK_NAME "rknn")
#list(APPEND LIB_ALG_SDK_NAME "ncealg")