name: host-build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/cmake/platforms/host.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . -v

    - name: Install
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --install . -v

    - name: Archive results
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ${{github.workspace}}/package