name: host-build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/cmake/platforms/host.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . -v

    - name: The job has failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{github.workspace}}

